### ISSUE TITLE
Add License Info

### ISSUE THREAD

**Issue by murphpdx** [meeting-guide/12-step-meeting-list#12]
There is no license information. Is this app open source?

**Comment by joshreisner** [comment]
This is a WordPress plugin and it is open source.

**Comment by FlipperPA** [comment]
Does a 3-Clause BSD license? If so I'd be happy to issue a PR with one. :)

**Comment by joshreisner** [comment]
Thanks Tim, but nah. I don’t think we should care how people want to use the product, even if they want to redistribute it as their own.

**Comment by johnfreed** [comment]
True, Josh, but since it's copyrighted (automatically) by you, you might
want to explicitly state it's Public Domain in that case.

**Comment by joshreisner** [comment]
You know what? I seem to have put 

	License: GPLv2 or later

in the plugin’s readme.txt, so clearly I don’t know what I’m talking about. 

Tim or John, if either of you want to do a PR on this I will approve it. You can choose the license, just a) make it consistent in the readme.txt as well, and b) just pick whatever you think the most ‘AA’ thing is.

**Comment by FlipperPA** [comment]
I was thinking the BSD license would be the most appropriate in line with the 4th tradition. Here's a good summary: https://fosswire.com/post/2007/04/the-differences-between-the-gpl-lgpl-and-the-bsd/ The one liner on how it works is, "here's the source code, do whatever you want with it, but if you have problems, it's your problem." I'll issue a PR with 3-clause BSD and if we want to discuss further, we can! Thanks, as always, Josh!

**Comment by joshreisner** [comment]
Thanks Tim!
