### ISSUE TITLE
Existing group information gets overwritten

### ISSUE THREAD

**Issue by tech2serve** [meeting-guide/12-step-meeting-list#16]
Adding the name of an existing group to a different meeting overwrites the previous group information. For example, if I have a Monday Meeting entry that includes group information for The Gagglers Group (to include a description, contact information, etc), and I go to record their Tuesday Meeting, when I add The Gagglers Group in the group information block, whatever I type (or don't type below), overwrites the existing post records for The Gagglers Group.

====
BTW, I've forked 12-step-meeting-list, and I'm starting local branch work to see if I can add to group management functions. I raise this issue no so much as to ask for a fix, but to start conversation about how the groups should be handled by the plugin. 

If I understand the basic structure, because groups are unique post types, we should be able to tie individual meetings to groups through meta data. Doing so, we should be able to change the meeting entry/edit form to have a drop-down to let users select which group a meeting is associated with. Likewise, we should be able to let the user add a group, and then bulk add meetings for that group, I think...

Any objections/thoughts about this basic approach?

**Comment by joshreisner** [comment]
Yes, I think you’re describing the intended behavior. Group names are unique, so if you add a new meeting, and use an existing group name, if you change the group description or contact information, this will then apply to all meetings that share this group.

I don’t think we need a new dropdown form element, the autocomplete appears to be working well.

I don’t know how bulk-adding meetings would work, other than using the import feature.

**Comment by tech2serve** [comment]
Thanks for getting back to me. I've been doing some more experimentation; I see where you're going with it.

Here is what I'm experiencing:
- If I begin typing the group name and use tab to auto complete the group name, the notes field gets filled in and that data is retained when the post is published. However, website and associated contact info does not appear to get filled in. The other contacts fields do seem to get filled in.
- If I type the complete group name without letting it auto complete (regardless if I hit tab after I type the last letter of the group name), neither the notes nor the metadata fill in. 
- Data that is not filled in from the database (or by retyping) gets overwritten with blanks.

An observation regarding the search for auto completion: Although most savvy users will figure this out, I noticed the auto complete does need the user to start typing th name as it already exists. For example, in my made-up "The Nomad Group", if I start typing "The...", auto complete finds "The Nomad Group". However, if I start typing "Nomad...", it does not. I'm not sure how many groups start with "The", but I know I've seen several. Another example (one of my past home groups): "Many a Strange Camel". Or, was it "Strange Camels"...? It was the former. It was the former, but if the person at CSO/Intergroup doesn't understand that...

Bulk adding meetings for a group may not be the the most exciting use of more group management features, but I believe being able to manage groups and see what meetings are associated with that group would be useful. I see where they are displayed in meetings once the association is made, but being able to change just group information without dealing with the meetings would be useful imo. 

Something else you'd rather I look at?

**Comment by johnfreed** [comment]
I just keep these in a flatfile database that I download/upload for fixes,
so no need for autocomplete.

I believe the search function works if you just type "Camel" and don't
worry about autocomplete?

**Comment by tech2serve** [comment]
Hi John, Are you saying you keep website information in a separate file? Obviously that is fine, but anyone trying out the plugin is going to be looking for those fields to remain filled in if she has filled them in before.

You're right about the search on the user side of the plugin; I'm seeing the issues on the admin side. I don't see a search option for that.

**Comment by joshreisner** [comment]
Hi @tech2serve, it sounds like there are three bugs here that you've found:

Regarding auto-filling the website / email / phone, that's a bug. Those fields were added later, and were not added to the autocomplete. Do you want to add those? It's in admin.js.

Regarding the auto-fill "Camel" issue, this actually uses the same library (Twitter Typeahead) as the search on the front-end does, but the difference is that the dropdown menu does not show on the admin side. To see what I mean, go to your search front end and see how when you start typing "Many" you see the dropdown and the suggestion, but when you just type "Camel" you only see the dropdown, but not the suggestion. Do you want to enable the dropdown in the admin screen and make it look nice? I believe it's just a CSS issue (admin.scss). To be consistent, this would also enable the dropdown for the location typeahead also on the admin page. 

Finally, if you type the full exact name of a group and tab out it should autofill the group, but I don't think that was ever programmed. Do you want to add that? See if there's something that can be reused from the typeahead autocomplete.

**Comment by tech2serve** [comment]
Hi Josh--

I'm happy to take a stab at those, and appreciate that you've given me some initial vectors. 

I'll have some learnin' to do, so don't expect anything by tomorrow morning ;-~

-Tim

**Comment by tech2serve** [comment]
I believe I have the first two bugs addressed; still testing...
Having addressed the second bug does mitigate the likelihood of the third bug being an issue for users. I'm still working on a solution as I believe it would be cleaner.

**Comment by joshreisner** [comment]
I think you fixed this in #17, thanks again
