### ISSUE TITLE
Is jQuery 3.x supported? 

### ISSUE THREAD

**Issue by faridoon** [meeting-guide/12-step-meeting-list#21]
The problem was the map view on the main meetings page. But adding jquery.migrate fixed it.

**Comment by joshreisner** [comment]
I'm not sure, the jQuery in here is pretty simple, so I doubt it'll cause a conflict with 3x. Bootstrap might be a different story, we are using Bootstrap 3.3. Not sure what its requirements are.

Be sure you're using wp_enqueue_script though and not including jQuery multiple times, that is a common problem.
