### ISSUE TITLE
Meets get linked together when the address is the same

### ISSUE THREAD

**Issue by murphpdx** [meeting-guide/12-step-meeting-list#25]
As a user I want to change meeting information without it changing other meetings at that location. 
OR 
I want to unlink meetings that are unrelated even if they are at the same location.

**Comment by joshreisner** [comment]
That’s right, meetings at the same address share location information. They can have different meeting info and group info however. Tell me more specifics about what you want to do and I can advise you better.

**Comment by joshreisner** [comment]
Closing issue, but happy to reopen if there’s more to discuss.

**Comment by murphpdx** [comment]
We have many meetings at the same location but they are unrelated. Our intergroup manager wants to be able to change information on one meeting without it having effects on the meetings. He is running into a lot of side effects because of this functionality. He is also experiencing an issue where meetings will go private when he makes a change to one. Can we turn the grouping off all together?

**Comment by joshreisner** [comment]
Hello, are you the same person Garry sent the email about and who also posted a ticket on the support threads?

To clarify:

Meetings at the same address are grouped together in the sense that they show up on the same map pin, that won't change. So two meetings will always share the same location name and notes if they're at the same address.

However, I made a change recently that I think will fix much of what you're talking about. Now, when you change the address of one meeting at a location, it still shows a checkbox to ask if you want to move all the meetings at that location, but now the checkbox is off by default.

I haven't seen an issue of meetings going private. Could you give me steps to reproduce that?
