### ISSUE TITLE
Feature request: Multi-select on 'Type'

### ISSUE THREAD

**Issue by jcorry** [meeting-guide/12-step-meeting-list#28]
Multiple selections (either via multiselect or checkboxes) for the Type would be very helpful. The Usecase for this is being able to select Literature (or Speaker, or Step Meeting, etc) AND apply the men/women/gay filter too.

Out hotline coordinator asked for this specifically. Right now the workaround is for the hotline volunteer to filter by 'Literature' and then observe in the list which meetings are marked 'men' or 'women'. The hotline coordinator would like to be able to filter more specifically.

I thought it was a useful feature so figured I'd bring it here.

**Comment by joshreisner** [comment]
This was actually a feature in 1.0, but users complained that it wasn't intuitive because it didn't match the behavior of the other dropdowns. I will see if I can implement it with a modifier key though, the command key is standard on macs for multiple selection.

**Comment by joshreisner** [comment]
The modifier key approach won't work on mobile, so that's a drawback, but it is how the current Atlanta meeting search works. Anyway this is a feature now as of 3.1.8!
