### ISSUE TITLE
Unauthenticated users can export Meetings CSV

### ISSUE THREAD

**Issue by DanielCoulbourne** [meeting-guide/12-step-meeting-list#29]
This actually just saved my butt since it's 2:30 am and my webmaster is asleep while I'm hacking on some stuff that required a fresh meeting export. Still, probably worth closing this hole, convenient as it may be 😉 

`/wp-admin/admin-ajax.php?action=tsml_ajax_csv`

is accessible to unauthenticated users and exports a full CSV. This ajax action is unaffected by sharing keys.

I may have some time to swing around and PR a fix for this tomorrow but I'm hacking on some other stuff right now and just wanted to get an issue in before I forgot.

**Comment by joshreisner** [comment]
ok thanks yeah -- now you must be logged in or have sharing open to see the CSV
