### ISSUE TITLE
Is it worth renaming the plugin folder name?

### ISSUE THREAD

**Issue by FlipperPA** [meeting-guide/12-step-meeting-list#3]
What do you think about renaming the repository from `plugin` to `12-step-meeting-list`? That way, you can clone it directly to the `wp-content/plugins` directory on a dev server without providing an additional path, and it makes it more explicitly named. Just a thought.

**Comment by joshreisner** [comment]
Ok you got it.

**Comment by FlipperPA** [comment]
Wow, thanks! That'll make my git checkout directories much easier to navigate.
