### ISSUE TITLE
Venue gets deleted when saving a new meeting

### ISSUE THREAD

**Issue by careytews** [meeting-guide/12-step-meeting-list#30]
Our "where to find" coordinator reported this to me, and I have verified it. In creating a new meeting, the venue information disappears after the first save (Publish), and the meeting is saved as a draft. When the meeting details are then updated to add the *same* venue info as before, the venue is still there after second save (Update).

Note: We *are* working with a fork of `12-step-meeting-list`, but the only change has been the label "Regions" in the lists has been changed to "Towns", so I hope it's not that that's causing it, but maybe it is? Which would be inconvenient. The idea of a "region" has been left alone everywhere else in the code. See the comparison [here](https://github.com/meeting-guide/12-step-meeting-list/compare/master...cauk-it:master) to see if it's relevant.

Steps to reproduce:
1. Add a meeting and save as usual.
2. Save.
3. The venue disappears.
4. Re-add the venue information.
5. Save again.
6. The venue is back.

Thanks very much for this wonderful plugin. We have received nothing but praise from most members around England and Wales for the new meeting list!

**Comment by joshreisner** [comment]
Hm, yes, definitely an issue in the main branch. Thanks for letting me know. I'll fix it as soon as I can.

FYI you don't need to fork the plugin to change that text. 

```php
if (function_exists('theme_override_tsml_strings')) {
    function theme_override_tsml_strings($translated_text, $text, $domain) {
        if ($domain == '12-step-meeting-list') {
            switch ($translated_text) {
                case 'Region':
                    return 'Town';
            }
        }
        return $translated_text;
    }
    add_filter('gettext', 'theme_override_tsml_strings', 20, 3);
}
```

**Comment by joshreisner** [comment]
Ok 3.1.13 is out and I believe the issue is fixed. Let me know!

PS we'd love to list your site on our [plugin homepage](https://wordpress.org/plugins/12-step-meeting-list/) if that's ok. What site is it?
