### ISSUE TITLE
Bug when filtering by location >=10 miles away

### ISSUE THREAD

**Issue by liberatus1** [meeting-guide/12-step-meeting-list#35]
I am working on an installation for South Palm Beach County, FL intergroup but I have come across what looks to be a bug that prevents moving toward production. 

Searching near zip 33428 within 5 miles (https://dev.aainpalmbeach.org/meetings/?tsml-day=5&tsml-distance=5&tsml-mode=location&tsml-query=Boca+Raton%2C+FL+33428%2C+USA) results in 5 meetings (all at same clubhouse) but changing the search to within 10 miles, or greater, removes 2 of those results (the Sober Sunset and Cheer up @ 10:13 groups). I have tried changing wordpress timezone settings etc. to no avail. What does work is changing the time of those groups to <4:00 PM. Another thing that works is adding to the existing filters > Any time > Night. When night is selected and filter by 10+ miles from 33428, then the missing meetings reappear.

**Comment by joshreisner** [comment]
Hey that sounds weird. Can you update to the latest and see if it's still a problem? Looks like you're on 3.3.3.

If it's still a problem after, can you attach a CSV or email one to info@meetingguide.org? I can look at it this weekend

**Comment by liberatus1** [comment]
Hi Josh, thanks for the quick reply! I just updated it and same issue persisting. Please find csv attached.
[meetings.zip](https://github.com/meeting-guide/12-step-meeting-list/files/3023185/meetings.zip)

**Comment by joshreisner** [comment]
OK thanks. I'll look at it tomorrow and recreate these steps and see what's going on

**Comment by liberatus1** [comment]
Thanks Josh, awesome plugin, looking forward to releasing our new site/list :)

**Comment by liberatus1** [comment]
Another strange thing - the only way I can make all meetings for all days appear is to set the wordpress setting 'Week starts on" = Saturday. If I set it to Sunday, and select filter=Any day, I only get a list of meetings from Sunday-Friday.

**Comment by joshreisner** [comment]
This is a super weird bug. At first I though what if the distance were doing string comparison, where "5" > "10", but that doesn't appear to be the case here. It's working fine on my computer.

Also what I'm observing on your site isn't quite that. At the link in the original post (https://dev.aainpalmbeach.org/meetings/?tsml-day=5&tsml-distance=5&tsml-mode=location&tsml-query=Boca+Raton%2C+FL+33428%2C+USA), I'm seeing five meetings at 1.3 distance (this matches my local environment as well). I see these same five meetings at 1, 2, and 5 radii.

When it goes to 10, I see six meetings. It seems that two of the 1.3 distance meetings were dropped, and only three new ones were added. On my local site I see 12 meetings total within 10mi, the five original ones plus 7 new ones.

To eliminate possible issues, could you try changing your theme to a different theme? Also if you have a plugin that could be affecting it, like a caching plugin, if you could try temporarily disabling those as well that'd be great, thanks.

If it'd be useful I can also set up a demo site on my end that we can try it on.

**Comment by liberatus1** [comment]
Josh, ok I am glad I am not the only one confused by this. I switched themes, played with settings, turned off any caching, nothing, just the same very strange behavior, so I decided to just create a fresh install and start from scratch and move stuff over. Working great now! Thank you!!

**Comment by joshreisner** [comment]
Great!

**Comment by billyjacoby** [comment]
hey guys, I know this issue was resolved.

liberatus1, I just wanted to reach out to you and let you know that if you need any help migrating to the app that id be more than happy to help. I went through this whole process for North Palm Beach County about two years ago.

Thanks guys!

**Comment by liberatus1** [comment]
Hi Billy,

Thanks for reaching out. Got it all figured out after getting rid of that bug, new site will be up for groups to review soon, yes I included a link in our site to the North Palm meetings page :)
