### ISSUE TITLE
Page titles / SEO issue

### ISSUE THREAD

**Issue by liberatus1** [meeting-guide/12-step-meeting-list#36]
Page titles are only updated when using the dropdown filters, in this case rendering an appropriate page title i.e. "Meetings in Boca Raton"

Direct hits i.e. "/meetings/?tsml-day=any&tsml-region=boca-raton" render the page title "Meetings Archive"

It will be very useful to provide search engines with the appropriate page title data which they will not receive if relying on the AJAX call.

**Comment by joshreisner** [comment]
I think that's just your theme! Try switching to another theme like TwentyFourteen and see if it still happens. For example, see the page titles on https://aasanjose.org/meetings

**Comment by liberatus1** [comment]
Ok nice, yes that or the Yoast plugin, thanks Josh!
