### ISSUE TITLE
Search button doesn't search when selecting search vs. nearby

### ISSUE THREAD

**Issue by mrlynn** [meeting-guide/12-step-meeting-list#7]
For example, visit http://aasepia.org/meetings

Type 19050 into search box and click Search button... the new functionality presents a drop down.  First, this confuses users - but I suppose we'll have to put a note or something on the site to help them.  Second, when you click Search from the drop down - the text you typed (19050) is cleared and all meetings are displayed.  Rather than the expected behavior which would be to accept the typed text and use that as the search string.

**Comment by joshreisner** [comment]
Sorry you don't like it, but this is working as intended. It's not a search button, it's a dropdown to help you switch between search modes.
